---
- name: Install S-Nail
  apt:
    name: s-nail
    state: present

- name: Configure S-Nail
  template:
    src: mailrc.s-nail.j2
    dest: /root/.mailrc

- name: Setup alternatives for MTA
  alternatives:
    name: mta
    link: /usr/sbin/sendmail
    path: /usr/bin/s-nail
