---
- name: Install MailX
  yum:
    name: mailx
    state: present
    update_cache: yes

- name: Configure MailX
  template:
    src: mailrc.mailx.j2
    dest: /etc/mail.rc

- name: Setup alternatives for MTA
  alternatives:
    name: mta
    link: /usr/sbin/sendmail
    path: /usr/bin/mailx
