---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "${MOLECULE_DISTRO:-ubuntu:latest}"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
provisioner:
  name: ansible
lint: |
  set -e
  ansible-lint .
